# for github.com
X-Cosmicrocks-Team: "acid"
# type should be one of [code, doc, config, tools, secrets]
# code will be the default value, if X-Cosmicrocks-Type is not found in .zappr.yml
X-Cosmicrocks-Type: code

approvals:
  groups:
    cosmicrocks:
      minimum: 2
      from:
        orgs:
          - cosmicrocks