apiVersion: "acid.cosmic.rocks/v1"
kind: postgresql
metadata:
  name: acid-minimal-cluster
spec:
  teamId: "acid"
  volume:
    size: 1Gi
  numberOfInstances: 2
  users:
    cosmicrocks:  # database owner
    - superuser
    - createdb
    foo_user: []  # role for application foo
  databases:
    foo: cosmicrocks  # dbname: owner
  preparedDatabases:
    bar: {}
  postgresql:
    version: "15"
