apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
  name: cosmicrocks-scdl8:users:admin
rules:
- apiGroups:
  - acid.cosmic.rocks
  resources:
  - postgresqls
  - postgresqls/status
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  name: cosmicrocks-scdl8:users:edit
rules:
- apiGroups:
  - acid.cosmic.rocks
  resources:
  - postgresqls
  verbs:
  - create
  - update
  - patch
  - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: cosmicrocks-scdl8:users:view
rules:
- apiGroups:
  - acid.cosmic.rocks
  resources:
  - postgresqls
  - postgresqls/status
  verbs:
  - get
  - list
  - watch
