{{ if .Values.rbac.createAggregateClusterRoles }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    app.kubernetes.io/name: {{ template "scdl8.name" . }}
    helm.sh/chart: {{ template "scdl8.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: {{ template "scdl8.fullname" . }}:users:admin
rules:
- apiGroups:
  - acid.cosmic.rocks
  resources:
  - postgresqls
  - postgresqls/status
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    app.kubernetes.io/name: {{ template "scdl8.name" . }}
    helm.sh/chart: {{ template "scdl8.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: {{ template "scdl8.fullname" . }}:users:edit
rules:
- apiGroups:
  - acid.cosmic.rocks
  resources:
  - postgresqls
  verbs:
  - create
  - update
  - patch
  - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
    app.kubernetes.io/name: {{ template "scdl8.name" . }}
    helm.sh/chart: {{ template "scdl8.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  name: {{ template "scdl8.fullname" . }}:users:view
rules:
- apiGroups:
  - acid.cosmic.rocks
  resources:
  - postgresqls
  - postgresqls/status
  verbs:
  - get
  - list
  - watch
{{ end }}
